import { STAGES, type Book, type Stage, type TaskTemplate } from "../types";

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: "tpl-id-docs",
    title: "Collect ID",
    books: ["residential", "commercial", "private"],
    unlockStages: ["lead", "application"],
    order: 8,
    kind: "standard",
  },
  {
    id: "tpl-income-docs",
    title: "Collect income docs",
    books: ["residential"],
    unlockStages: ["lead", "application"],
    order: 10,
    kind: "standard",
  },
  {
    id: "tpl-application-package",
    title: "Build application package",
    books: ["residential"],
    unlockStages: ["application"],
    order: 20,
    kind: "standard",
  },
  {
    id: "tpl-stress-test",
    title: "Record stress test / qualifying rate",
    books: ["residential"],
    unlockStages: ["application"],
    order: 25,
    kind: "standard",
  },
  {
    id: "tpl-submit-lender",
    title: "Submit to lender",
    books: ["residential", "commercial", "private"],
    unlockStages: ["application"],
    order: 30,
    kind: "standard",
  },
  {
    id: "tpl-commitment",
    title: "Receive and review commitment",
    books: ["residential", "commercial", "private"],
    unlockStages: ["submitted", "conditional"],
    order: 40,
    kind: "standard",
  },
  {
    id: "tpl-appraisal",
    title: "Order appraisal",
    books: ["residential", "commercial"],
    unlockStages: ["submitted", "conditional"],
    order: 50,
    kind: "standard",
  },
  {
    id: "tpl-title",
    title: "Title search",
    books: ["residential"],
    unlockStages: ["conditional"],
    order: 60,
    kind: "standard",
  },
  {
    id: "tpl-outstanding",
    title: "Clear outstanding conditions",
    books: ["residential", "commercial"],
    unlockStages: ["conditional"],
    order: 70,
    kind: "standard",
  },
  {
    id: "tpl-aml-check",
    title: "AML / ID verification",
    books: ["residential", "commercial", "private"],
    unlockStages: ["clear-to-close"],
    order: 71,
    kind: "compliance",
  },
  {
    id: "tpl-insurance",
    title: "Confirm property insurance",
    books: ["residential", "private"],
    unlockStages: ["conditional", "clear-to-close"],
    order: 80,
    kind: "standard",
  },
  {
    id: "tpl-lawyer",
    title: "Instruct lawyer / solicitor",
    books: ["residential", "commercial"],
    unlockStages: ["conditional", "clear-to-close"],
    order: 90,
    kind: "standard",
  },
  {
    id: "tpl-pickup",
    title: "Confirm solicitor pickup",
    books: ["residential", "commercial", "private"],
    unlockStages: ["funded", "review"],
    order: 200,
    kind: "standard",
  },
  {
    id: "tpl-invoice-match",
    title: "Match lender invoice",
    books: ["residential", "commercial", "private"],
    unlockStages: ["funded", "review"],
    order: 210,
    kind: "standard",
  },
  {
    id: "tpl-aml-closeout",
    title: "AML / compliance close-out",
    books: ["residential", "commercial", "private"],
    unlockStages: ["funded", "review"],
    order: 220,
    kind: "compliance",
  },
  {
    id: "tpl-rent-roll",
    title: "Collect rent roll and leases",
    books: ["commercial"],
    unlockStages: ["lead", "application"],
    order: 12,
    kind: "standard",
  },
  {
    id: "tpl-noi",
    title: "Complete NOI worksheet",
    books: ["commercial"],
    unlockStages: ["application"],
    order: 18,
    kind: "standard",
  },
  {
    id: "tpl-dscr",
    title: "Record DSCR",
    books: ["commercial"],
    unlockStages: ["application", "submitted"],
    order: 22,
    kind: "standard",
  },
  {
    id: "tpl-environmental",
    title: "Environmental / Phase I",
    books: ["commercial"],
    unlockStages: ["submitted", "conditional"],
    order: 55,
    kind: "standard",
  },
  {
    id: "tpl-term-sheet",
    title: "Issue term sheet",
    books: ["private"],
    unlockStages: ["lead", "application"],
    order: 11,
    kind: "standard",
  },
  {
    id: "tpl-exit",
    title: "Document exit strategy",
    books: ["private"],
    unlockStages: ["application"],
    order: 16,
    kind: "standard",
  },
  {
    id: "tpl-broker-fee",
    title: "Broker fee agreement",
    books: ["private"],
    unlockStages: ["application"],
    order: 19,
    kind: "standard",
  },
  {
    id: "tpl-private-lawyer",
    title: "Instruct lawyer / solicitor",
    books: ["private"],
    unlockStages: ["application", "conditional"],
    order: 24,
    kind: "standard",
  },
  {
    id: "tpl-second-position",
    title: "Title / second-position search",
    books: ["private"],
    unlockStages: ["application", "conditional"],
    order: 26,
    kind: "standard",
  },
];

export function templatesForBook(book: Book): TaskTemplate[] {
  return TASK_TEMPLATES.filter((template) => template.books.includes(book)).sort(
    (a, b) => a.order - b.order,
  );
}

export function earliestUnlockIndex(unlockStages: Stage[]): number {
  return Math.min(...unlockStages.map((stage) => STAGES.indexOf(stage)));
}
